# Generated by Django 4.0.6 on 2022-08-18 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=50)),
                ('t_description', models.TextField()),
                ('t_venue', models.CharField(max_length=100)),
                ('t_start_date', models.DateField(default=django.utils.timezone.now)),
                ('t_end_date', models.DateField(default=django.utils.timezone.now)),
                ('t_age_group', models.CharField(max_length=20)),
            ],
        ),
    ]
