# Generated by Django 4.0.6 on 2022-08-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.CharField(max_length=10)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('Experience', models.CharField(max_length=20)),
                ('About_Coach', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Membership_plan',
            fields=[
                ('Plan_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Duration', models.CharField(max_length=45)),
                ('Charge', models.IntegerField(default=0)),
                ('Description', models.TextField()),
            ],
        ),
    ]
