# Generated by Django 4.0.6 on 2022-08-10 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('feedback', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
