# Generated by Django 4.0.6 on 2022-08-10 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_Detail',
            fields=[
                ('member_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=45)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=6)),
                ('plan_name', models.CharField(max_length=50)),
                ('transaction_no', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
